### ISSUE TITLE
Cannot read properties of undefined (reading 'href')

### ISSUE THREAD

**Issue by tensor365** [andreax79/airflow-code-editor#62]
Hi, 

We wanna try your code editor, we had no troubles during installation. But when we tried to change theme. We've got this error: 

TypeError: Cannot read properties of undefined (reading 'href')
    at Proxy.setTheme (Editor.vue:178:116)
    at Proxy.updateSettings (Editor.vue:188:18)
    at tn (runtime-core.esm-bundler.js:155:22)
    at pt (runtime-core.esm-bundler.js:164:21)
    at Mc (runtime-core.esm-bundler.js:721:9)
    at Proxy.ok (SettingsDialog.vue:68:18)
    at b.onClick.t.<computed>.t.<computed> (SettingsDialog.vue:21:27)
    at tn (runtime-core.esm-bundler.js:155:22)
    at pt (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.n (runtime-dom.esm-bundler.js:369:13)

in console of web interface. Is there anything I miss ?

Thank

**Comment by andreax79** [comment]
Hi,

Thank you for finding the bug.
Setting theme was not working in the last versions.
Please check if with the last version (7.1.1) the bug is resolved.

**Comment by tensor365** [comment]
Hi, 

Thank for your answer. The bug is indeed resolved by upgrading to new version.
